-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 10:33:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `optica` ;

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `piso` INT NOT NULL,
  `puerta` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `fax` INT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Marcas` (
  `idMarca` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`),
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `optica`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idProveedor_idx` ON `optica`.`Marcas` (`idProveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optica`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Productos` (
  `idProducto` INT NOT NULL,
  `IdMarca` INT NOT NULL,
  `precio` DECIMAL(5) NOT NULL,
  `graduacion_D` DECIMAL(5) NOT NULL,
  `graduacion_I` DECIMAL(5) NOT NULL,
  `tipo_montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidrio_D` VARCHAR(45) NOT NULL,
  `color_vidrio_I` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idMarca`
    FOREIGN KEY (`IdMarca`)
    REFERENCES `optica`.`Marcas` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idMarca_idx` ON `optica`.`Productos` (`IdMarca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `recomendado_por` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Compra` (
  `idCompra` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idVendedor` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `optica`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `optica`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCliente_idx` ON `optica`.`Compra` (`idCliente` ASC) VISIBLE;

CREATE INDEX `fk_Compra_Productos1_idx` ON `optica`.`Compra` (`idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optica`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Vendedor` (
  `idVendedor` INT NOT NULL,
  `idCompra` INT NOT NULL,
  CONSTRAINT `idVendedor`
    FOREIGN KEY (`idCompra`)
    REFERENCES `optica`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idVendedor_idx` ON `optica`.`Vendedor` (`idCompra` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
